import React, {useState, useEffect} from "react"

import "./About.css"


export default function About() {
    return (
        <div>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Omnis aspernatur, porro deserunt esse provident ut iure tempora voluptatum harum quod nihil doloremque, accusamus distinctio, pariatur praesentium corporis consectetur dolor suscipit?
            Vero dolore beatae maiores dolor doloribus voluptate magnam ut, exercitationem, eum, rerum ipsa unde consequatur odit maxime hic repellat iure dolorem? Cumque sed beatae sequi dolores, numquam animi assumenda minima!
            A hic inventore, aliquam optio modi eius? Nemo consequatur, dolorum culpa molestiae sit impedit sunt. Odio inventore alias, amet cumque reiciendis voluptatem, dolorem at et explicabo earum dolore saepe fugiat?
            Ratione, itaque. Neque assumenda quibusdam dolorum ullam ab veniam voluptas error ratione culpa quae blanditiis, reiciendis alias, molestiae nam officiis maiores. Eligendi non distinctio rerum, incidunt vel maiores delectus commodi!
            Libero beatae ullam quas nisi minima officia at quod omnis praesentium, repellat neque fugiat nesciunt? Ut minus est quos possimus ea tenetur doloremque modi quod voluptatum tempora! A, consequatur corrupti.
            Omnis fuga illo officia necessitatibus saepe soluta eligendi dignissimos sint exercitationem eveniet, rerum fugiat officiis? Nemo illum eos modi odio dolores ratione velit, reiciendis odit libero hic ipsum praesentium optio?
            Provident unde ad hic omnis vitae, totam odit aliquid nam vel odio inventore veniam commodi eos perferendis placeat! Officiis, hic cumque porro cum alias facilis blanditiis odio nobis nam saepe.
            Architecto sapiente aut delectus laborum ratione unde blanditiis, quasi, deleniti at voluptatibus quas. Omnis necessitatibus tempore, perspiciatis vel reiciendis repellendus eveniet amet ab beatae quae aperiam repudiandae cum qui laborum?
            Accusantium vitae facere dignissimos sequi exercitationem, adipisci non inventore. Porro nulla vitae, officiis hic id quis fuga, delectus, odio laborum officia qui ipsum. Sunt maxime est laborum non sit tenetur.
            Impedit quos architecto autem, nobis at facere vel! Facere autem tempora aliquam, voluptas molestiae consequuntur illum officia rerum laborum accusantium dolorum alias libero repellendus voluptates voluptatem quae veniam voluptate quaerat.
            Labore reprehenderit rerum, esse, nobis ad earum obcaecati repellendus recusandae at reiciendis maiores voluptatum dicta temporibus velit sunt sit quas nesciunt quidem dolore. Voluptate, sunt quos? Dolorum aut est blanditiis!
            Atque vero expedita quos laboriosam quasi tempore in et ad consequuntur dignissimos incidunt cumque maiores accusamus aliquid labore tenetur minima minus rerum, necessitatibus esse excepturi quidem optio odit? Ipsum, vero.
            Eligendi reiciendis ex aliquam amet provident esse fugit hic quaerat nihil perferendis, possimus quasi debitis totam delectus repellat aperiam culpa dolor non quam. Corrupti vitae quas voluptatem maxime inventore. Hic.
            Consectetur sapiente voluptate cumque ex explicabo, optio aliquam sequi fugiat veniam quod ipsam mollitia. Nostrum quod consequatur expedita excepturi totam saepe veritatis ea, nulla voluptatibus eaque pariatur autem. Nisi, repudiandae!
            Obcaecati corporis veritatis iure ut repellat. Nesciunt debitis beatae eaque non iste! Quas porro fuga laudantium quo amet, quae, ratione vero hic beatae quia neque quos molestiae consequatur, aut vel?
            Labore reiciendis sit architecto maxime iure! Temporibus ducimus sed harum fugit, libero natus ratione sint earum veniam quod doloremque eum rem ea quos incidunt repellendus nesciunt quo, porro iure laudantium.
            Asperiores quibusdam sapiente veritatis facilis assumenda velit error ex magnam nostrum porro! Sit id adipisci consectetur dicta aliquid blanditiis laborum, quae, quo illum iste veritatis perferendis animi eligendi qui. Iusto.
            Ipsam nam in repellat molestias odit. Perferendis nisi nesciunt ut perspiciatis consectetur vel officia consequuntur, earum nostrum. Nobis magni fugit, odit dolorem et laboriosam iure impedit perspiciatis totam? Quaerat, harum!
            Eos ipsa iste eveniet, ipsum qui corrupti laudantium dolores ipsam perferendis, quia eligendi similique maiores cupiditate sed nulla quisquam. Possimus minima sapiente eaque eum maiores nesciunt delectus? Cumque, provident illum.
            Nobis ex repellendus, corporis ad, consequuntur odit veritatis sint explicabo molestias recusandae esse quod quam expedita, dignissimos omnis ratione reiciendis laboriosam corrupti. Iure velit quia autem magni voluptatum eum natus?
            Ipsum dolores delectus illo excepturi, sit error voluptas, a ab provident officia molestiae. Eum culpa, amet officia aspernatur aut autem. Enim nihil dignissimos consectetur ducimus maxime id optio. Ipsum, facilis?
            Amet neque ex alias asperiores nostrum illo laudantium eum mollitia quae tempora, ratione eveniet deserunt officiis nesciunt a reprehenderit beatae impedit? Incidunt, ut ducimus? Aperiam, porro nesciunt! Voluptatibus, minima soluta.
            Itaque sequi hic dolorem saepe voluptas repellat perspiciatis enim eaque quia voluptate, nulla ipsum, corrupti error natus, ratione quo quasi. Laudantium atque quasi maxime dicta sapiente, reprehenderit blanditiis iste. Libero.
            Laborum suscipit nihil aperiam porro consequatur accusamus repellendus, sit commodi adipisci distinctio in beatae ducimus quis exercitationem quas! Ad, sapiente. Incidunt non tempore, numquam omnis provident quisquam commodi temporibus debitis!
            Accusantium excepturi modi molestiae in maxime sunt iure corrupti ullam dolor quis iusto numquam mollitia quam eius, ratione quia fugit minus eum ab aperiam odit sapiente corporis voluptas aliquam! Impedit.
            Cum velit odio, expedita corrupti sed distinctio at magnam quos debitis, vero delectus ea aliquid fugit quaerat rem quam culpa optio eius voluptates ipsam! Facilis dolorem blanditiis excepturi nulla omnis.
            Id ipsum architecto maxime eveniet molestias aliquid quos minus blanditiis! Nesciunt id quae aut sapiente, odit accusantium esse? Asperiores hic laudantium doloribus molestiae voluptatum omnis a sed nihil, est quos.
            Aspernatur pariatur non beatae perferendis laudantium nulla necessitatibus, molestiae hic voluptatem amet commodi consectetur ad similique rerum quibusdam modi natus id sed eveniet magni illo qui provident eos? Alias, eaque.
            Hic quas minima incidunt explicabo at nesciunt ipsam doloremque laboriosam eaque veritatis voluptates fuga repudiandae, maxime reprehenderit eos accusantium cum placeat sapiente odio necessitatibus in eligendi! Recusandae ex rem beatae.
            Libero enim, voluptatem eveniet deserunt quisquam architecto mollitia cum asperiores sunt officiis, velit eum ullam corrupti sequi explicabo aperiam fugit itaque temporibus. Tenetur facilis tempora autem. Rerum in dolor tenetur!
            Corporis, praesentium, eligendi earum magni consequatur vel voluptates distinctio voluptatum, nisi eum illum ipsa excepturi vero. Vero repellat laudantium, libero illum cupiditate tempore repudiandae molestias maiores dolore a aut exercitationem.
            Impedit debitis amet expedita voluptatum aspernatur saepe accusamus? Corporis, autem. Aut suscipit dolorem porro magni rerum adipisci, tempore maxime velit maiores debitis accusantium? Dolores dolorem delectus illo quaerat fugit quasi?
            Facere suscipit placeat aliquid accusantium, repudiandae, earum, facilis praesentium enim labore laborum tempora quidem. Quam quis dolore quia, velit aliquid error blanditiis. Ullam repellendus rem provident laudantium fugiat recusandae commodi!
            Consectetur itaque alias doloribus est reprehenderit cum minus soluta optio assumenda delectus, voluptatum, suscipit sunt dicta quisquam recusandae dolor id repellendus fuga at, illum nobis esse eveniet libero. Numquam, saepe!
            Vel sequi expedita quod officia laborum optio omnis, harum maiores. Doloremque, quos? Ab assumenda ullam fuga rem maiores nisi nobis asperiores, delectus minus id aperiam enim quas distinctio sapiente adipisci.
            Facere magni laborum, ratione accusantium tenetur voluptatibus ex quibusdam natus itaque, nemo deserunt consectetur dolorum aliquam commodi provident error est rerum expedita voluptatum quidem. Autem tenetur officiis quas maiores adipisci.
            Ullam, ducimus expedita dicta blanditiis aut dolorem quaerat dolores! Error optio ea iste neque facilis, minus doloremque, officia dolores adipisci nostrum tempora libero consequatur facere eligendi recusandae repudiandae. Sint, ratione!
            Laudantium suscipit iure labore eum, magnam in repellendus, aperiam alias beatae dicta ipsum error tenetur cupiditate quae ab sint ipsam natus impedit assumenda repellat officiis quisquam aliquam. Inventore, id provident.
            Ipsa labore, deleniti ab pariatur ducimus nulla adipisci dolorem ratione obcaecati repudiandae laboriosam quia sint eaque cum voluptates, nihil nobis velit, tempora animi laudantium sit corporis accusamus nemo qui? Ex.
            Quae in totam eaque velit aperiam quas temporibus a accusamus. Quasi laborum odit distinctio consequatur, dolorem fuga recusandae consequuntur, excepturi quae repellat beatae error neque! Illum quae ut et commodi?
            Voluptatem rem, illum consequatur ullam similique eius esse nobis explicabo ipsam, hic officia quo laudantium id fugiat aliquam, aperiam neque nisi qui corporis voluptates quasi quis deserunt necessitatibus. Deserunt, hic.
            Quasi ipsam totam expedita soluta provident aliquam quis, animi dolorem voluptatem debitis recusandae pariatur dolore libero possimus est optio nam aut, quo quidem. Ut nostrum in excepturi cumque! Inventore, culpa?
            Iusto enim ipsam sit vitae quis dignissimos aperiam a perspiciatis minima ut rerum itaque architecto distinctio magni ea suscipit sunt ipsum placeat unde perferendis, provident quibusdam explicabo, expedita fugiat. At.
            Reprehenderit nemo quidem eaque quod ducimus dolor blanditiis dignissimos et? Reiciendis sint tempore harum nisi dolorum, sapiente officiis ea! Sequi fuga asperiores ipsa atque soluta commodi magnam illo quasi. Facere?
            Quidem pariatur nisi repudiandae rem recusandae expedita, aspernatur deserunt quisquam impedit, a cum, blanditiis corrupti debitis dolorum dicta temporibus! Culpa nobis placeat unde consequatur reprehenderit iste quo sunt modi sapiente!
            Voluptate saepe labore voluptates libero sint veritatis, possimus explicabo, nihil asperiores id amet nemo quia atque fuga reiciendis mollitia eligendi et suscipit. Laborum similique impedit porro sed ullam amet illum.
            Voluptatibus illum modi culpa ducimus accusantium. Laborum libero, odio dolor quibusdam, minima a doloribus consequatur nulla dolorem alias beatae iste eveniet dicta aut in placeat reiciendis exercitationem. Assumenda, vitae veniam?
            Earum officiis expedita eos amet beatae nisi libero quam a ea, facilis, nam quod, illo iusto. Aliquid omnis aspernatur sapiente temporibus. Quos, laboriosam placeat perferendis quidem atque nobis ipsam! Molestiae!
            Est mollitia voluptatum repudiandae nisi iure voluptate enim soluta, officia vitae, minus ipsum earum nesciunt voluptates praesentium magnam ea repellendus quam beatae necessitatibus vero molestiae error ducimus? Sint, delectus iusto.
            Odio doloremque esse natus maxime tempore ab ea incidunt ratione facilis magnam, voluptate adipisci? Doloribus, reiciendis quam. Doloremque, veritatis pariatur beatae suscipit assumenda labore sed unde, tempore, obcaecati voluptate accusantium.
        </div>
    )
}